use crate::{
    geometry::mesh::PrimitiveMesh,
    io::NetCDF,
    // io::netcdf::{
    //     NC_DOUBLE, NC_FLOAT, NC_GLOBAL, NC_INT, nc_close, nc_create, nc_def_dim, nc_def_var,
    //     nc_enddef, nc_put_att_float, nc_put_att_text, nc_put_att_uint, nc_put_var_double,
    //     nc_put_var_int,
    // },
};
use std::ffi::NulError;

use std::ffi::{CString, c_int};
use std::{io::Result as ResultIO, path::Path};

pub trait Write<P>
where
    P: AsRef<Path>,
{
    fn write(self, output: P) -> Result<NetCDF, NulError>;
}

// impl<const D: usize, const I: usize, const M: usize, const N: usize, P, T> Write<P>
//     for PrimitiveMesh<D, I, M, N, T>
// where
//     P: AsRef<Path>,
// {
//     fn write(self, output: P) -> Result<NetCDF, NulError> {
//         todo!()
//     }
// }

impl<const D: usize, const I: usize, const M: usize, const N: usize, P, T> Write<P>
    for &PrimitiveMesh<D, I, M, N, T>
where
    P: AsRef<Path>,
{
    fn write(self, output: P) -> Result<NetCDF, NulError> {
        let path = output.as_ref().to_str().unwrap();
        let mut netcdf = NetCDF::create(path)?;
        netcdf.global()?;
        Ok(netcdf)
    }
}

// need path as argument
// impl<const D: usize, const I: usize, const M: usize, const N: usize, P, T> From<&PrimitiveMesh> for NetCDF {
//     fn from(mesh: &PrimitiveMesh) -> Self {
//         let mut netcdf = NetCDF::create("output.exo").unwrap();
//         netcdf.global().unwrap();
//         netcdf
//     }
// }

// pub fn write<const D: usize, const I: usize, const M: usize, const N: usize, P, T>(
//     mesh: &PrimitiveMesh<D, I, M, N, T>,
//     path: P,
// ) -> ResultIO<()>
// where
//     P: AsRef<Path>,
//     T: Copy + Into<usize>,
// {
    // let path = path.as_ref().to_str().unwrap();
    // let path = CString::new(path).unwrap();

    // let mut ncid = 0;
    // let status = unsafe { nc_create(path.as_ptr(), 0, &mut ncid) };
    // assert_eq!(status, 0);

    // let api_version: [f32; 1] = [8.25];
    // let file_size: [u32; 1] = [1];
    // let floating_point_word_size: [u32; 1] = [8];
    // let version: [f32; 1] = [8.25];

    // let title = CString::new(
    //     "autotwin.automesh, version 0.3.10, autogenerated on 2026-05-20 16:40:32.893159480 UTC",
    // )
    // .unwrap();

    // let name = CString::new("api_version").unwrap();
    // let status = unsafe {
    //     nc_put_att_float(
    //         ncid,
    //         NC_GLOBAL,
    //         name.as_ptr(),
    //         NC_FLOAT,
    //         1,
    //         api_version.as_ptr(),
    //     )
    // };
    // assert_eq!(
    //     status, 0,
    //     "nc_put_att_float failed for api_version with status={status}"
    // );

    // let name = CString::new("file_size").unwrap();
    // let status = unsafe {
    //     nc_put_att_uint(
    //         ncid,
    //         NC_GLOBAL,
    //         name.as_ptr(),
    //         NC_INT,
    //         1,
    //         file_size.as_ptr(),
    //     )
    // };
    // assert_eq!(
    //     status, 0,
    //     "nc_put_att_uint failed for file_size with status={status}"
    // );

    // let name = CString::new("floating_point_word_size").unwrap();
    // let status = unsafe {
    //     nc_put_att_uint(
    //         ncid,
    //         NC_GLOBAL,
    //         name.as_ptr(),
    //         NC_INT,
    //         1,
    //         floating_point_word_size.as_ptr(),
    //     )
    // };
    // assert_eq!(
    //     status, 0,
    //     "nc_put_att_uint failed for floating_point_word_size with status={status}"
    // );

    // let name = CString::new("title").unwrap();
    // let status = unsafe {
    //     nc_put_att_text(
    //         ncid,
    //         NC_GLOBAL,
    //         name.as_ptr(),
    //         title.as_bytes().len(),
    //         title.as_ptr(),
    //     )
    // };
    // assert_eq!(
    //     status, 0,
    //     "nc_put_att_text failed for title with status={status}"
    // );

    // let name = CString::new("version").unwrap();
    // let status = unsafe {
    //     nc_put_att_float(
    //         ncid,
    //         NC_GLOBAL,
    //         name.as_ptr(),
    //         NC_FLOAT,
    //         1,
    //         version.as_ptr(),
    //     )
    // };
    // assert_eq!(
    //     status, 0,
    //     "nc_put_att_float failed for version with status={status}"
    // );

    // let mut dimid: c_int = 0;
    // let name = CString::new("num_dim").unwrap();
    // let status = unsafe { nc_def_dim(ncid, name.as_ptr(), D as u64, &mut dimid) };
    // assert_eq!(status, 0);

    // // Mesh is only built for 1 block, would need to implement Meshes

    // let name = CString::new("num_elem").unwrap();
    // let status = unsafe {
    //     nc_def_dim(
    //         ncid,
    //         name.as_ptr(),
    //         mesh.connectivity().len() as u64,
    //         &mut dimid,
    //     )
    // };
    // assert_eq!(status, 0);
    // // let num_elem_dim_id = dimid;

    // let name = CString::new("num_el_blk").unwrap();
    // let status = unsafe { nc_def_dim(ncid, name.as_ptr(), 1_u64, &mut dimid) };
    // assert_eq!(status, 0);
    // let num_el_blk_dim_id = dimid;

    // let name = CString::new("num_el_in_blk1").unwrap();
    // let status = unsafe {
    //     nc_def_dim(
    //         ncid,
    //         name.as_ptr(),
    //         mesh.connectivity().len() as u64,
    //         &mut dimid,
    //     )
    // };
    // assert_eq!(status, 0);
    // let num_el_in_blk1_dim_id = dimid;

    // let name = CString::new("num_nod_per_el1").unwrap();
    // let status = unsafe { nc_def_dim(ncid, name.as_ptr(), N as u64, &mut dimid) };
    // assert_eq!(status, 0);
    // let num_nod_per_el1_dim_id = dimid;

    // let name = CString::new("num_nodes").unwrap();
    // let status = unsafe {
    //     nc_def_dim(
    //         ncid,
    //         name.as_ptr(),
    //         mesh.number_of_nodes() as u64,
    //         &mut dimid,
    //     )
    // };
    // assert_eq!(status, 0);
    // let num_nodes_dim_id = dimid;

    // let name = CString::new("time_step").unwrap();
    // let status = unsafe { nc_def_dim(ncid, name.as_ptr(), 0_u64, &mut dimid) };
    // assert_eq!(status, 0);

    // let mut varid: c_int = 0;

    // let cname = CString::new("eb_prop1").unwrap();
    // let status = unsafe {
    //     nc_def_var(
    //         ncid,
    //         cname.as_ptr(),
    //         NC_INT,
    //         1,
    //         [num_el_blk_dim_id].as_ptr(),
    //         &mut varid,
    //     )
    // };
    // assert_eq!(status, 0, "nc_def_var failed with status={status}");
    // let eb_prop_1_varid = varid;

    // let cname = CString::new("connect1").unwrap();
    // let status = unsafe {
    //     nc_def_var(
    //         ncid,
    //         cname.as_ptr(),
    //         NC_INT,
    //         2,
    //         [num_el_in_blk1_dim_id, num_nod_per_el1_dim_id].as_ptr(),
    //         &mut varid,
    //     )
    // };
    // assert_eq!(status, 0, "nc_def_var failed with status={status}");
    // let connect1_varid = varid;

    // let attr_name = CString::new("elem_type").unwrap();
    // let attr_value = match [D, M] {
    //     [3, 2] => CString::new("TRI3").unwrap(),
    //     _ => panic!(),
    // };
    // let status = unsafe {
    //     nc_put_att_text(
    //         ncid,
    //         connect1_varid,
    //         attr_name.as_ptr(),
    //         4,
    //         attr_value.as_ptr(),
    //     )
    // };
    // assert_eq!(status, 0, "nc_put_att_text failed with status={status}");

    // let mut varids = Vec::new();

    // match D {
    //     3 => {
    //         for name in ["coordx", "coordy", "coordz"] {
    //             let dimids = [num_nodes_dim_id];
    //             let cname = CString::new(name).unwrap();

    //             let status = unsafe {
    //                 nc_def_var(
    //                     ncid,
    //                     cname.as_ptr(),
    //                     NC_DOUBLE,
    //                     1,
    //                     dimids.as_ptr(),
    //                     &mut varid,
    //                 )
    //             };
    //             assert_eq!(status, 0, "nc_def_var failed with status={status}");
    //             varids.push(varid);
    //         }
    //     }
    //     _ => unimplemented!(),
    // }

    // let status = unsafe { nc_enddef(ncid) };
    // assert_eq!(status, 0, "nc_enddef failed with status={status}");

    // let eb_prop_1 = [1 as c_int];
    // let status = unsafe { nc_put_var_int(ncid, eb_prop_1_varid, eb_prop_1.as_ptr()) };
    // assert_eq!(
    //     status, 0,
    //     "nc_put_var_int failed for eb_prop_1 with status={status}"
    // );

    // let connect1: Vec<c_int> = mesh
    //     .connectivity()
    //     .iter()
    //     .flat_map(|nodes| nodes.iter().map(|&node| node.into() as c_int + 1))
    //     .collect();

    // let status = unsafe { nc_put_var_int(ncid, connect1_varid, connect1.as_ptr()) };
    // assert_eq!(status, 0, "nc_put_var_int failed with status={status}");

    // <[Vec<f64>; D]>::from(mesh.coordinates())
    //     .into_iter()
    //     .zip(varids)
    //     .for_each(|(coordinate, varid)| {
    //         let status = unsafe { nc_put_var_double(ncid, varid, coordinate.as_ptr()) };
    //         assert_eq!(status, 0, "nc_put_var_double failed with status={status}");
    //     });

    // let status = unsafe { nc_close(ncid) };
    // assert_eq!(status, 0, "nc_close failed with status={status}");

//     Ok(())
// }
