use crate::geometry::mesh::PrimitiveMesh;

use std::ffi::{CStr, CString, c_char, c_int, c_ulong};
use std::{io::Result as ResultIO, path::Path};

// maybe an exodus module in geometry/mesh/ and another in fem/ and in vem/ etc.
// the one in mesh would be more like genesis files
// the ones in fem/ and vem/ would be more like exodus files (with output variables and timesteps)

unsafe extern "C" {
    pub fn ex_create_int(
        path: *const c_char,
        mode: c_int,
        comp_ws: *mut c_int,
        io_ws: *mut c_int,
    ) -> c_int;
    pub fn ex_close(exoid: c_int) -> c_int;
}

#[test]
fn test_exodus_create_close() {
    use std::ffi::CString;

    let path = CString::new("target/test.exo").unwrap();
    let mut comp_ws = 8;
    let mut io_ws = 8;

    let exoid = unsafe { ex_create_int(path.as_ptr(), 0, &mut comp_ws, &mut io_ws) };
    assert!(exoid >= 0, "ex_create failed with exoid={exoid}");

    let status = unsafe { ex_close(exoid) };
    assert_eq!(status, 0, "ex_close failed with status={status}");
}

unsafe extern "C" {
    pub fn nc_inq_libvers() -> *const c_char;
}

#[test]
fn test_netcdf_lib_version() {
    let ptr = unsafe { nc_inq_libvers() };
    assert!(!ptr.is_null(), "nc_inq_libvers returned null");

    let version = unsafe { CStr::from_ptr(ptr) }
        .to_str()
        .expect("netCDF version string was not valid UTF-8");

    println!("netCDF version: {version}");
    assert!(!version.is_empty(), "netCDF version string was empty");
}

unsafe extern "C" {
    pub fn nc_create(path: *const c_char, cmode: c_int, ncidp: *mut c_int) -> c_int;
    pub fn nc_close(ncid: c_int) -> c_int;
    pub fn nc_def_dim(ncid: c_int, name: *const c_char, len: c_ulong, idp: *mut c_int) -> c_int;
    pub fn nc_def_var(
        ncid: c_int,
        name: *const c_char,
        xtype: c_int,
        ndims: c_int,
        dimidsp: *const c_int,
        varidp: *mut c_int,
    ) -> c_int;
    pub fn nc_enddef(ncid: c_int) -> c_int;
    pub fn nc_put_att_text(
        ncid: c_int,
        varid: c_int,
        name: *const c_char,
        len: usize,
        value: *const c_char,
    ) -> c_int;
    pub fn nc_put_var_int(ncid: c_int, varid: c_int, op: *const c_int) -> c_int;
    pub fn nc_put_var_float(ncid: c_int, varid: c_int, op: *const f32) -> c_int;
    pub fn nc_put_var_double(ncid: c_int, varid: c_int, op: *const f64) -> c_int;
    pub fn nc_put_att_float(
        ncid: c_int,
        varid: c_int,
        name: *const c_char,
        xtype: c_int,
        len: usize,
        op: *const f32,
    ) -> c_int;

    pub fn nc_put_att_uint(
        ncid: c_int,
        varid: c_int,
        name: *const c_char,
        xtype: c_int,
        len: usize,
        op: *const u32,
    ) -> c_int;
}

pub const NC_GLOBAL: c_int = -1;
pub const NC_FLOAT: i32 = 5;
pub const NC_DOUBLE: i32 = 6;
pub const NC_INT: i32 = 4;
pub const NC_CHAR: i32 = 2;

#[test]
fn test_netcdf() {
    let path = CString::new("target/test.nc").unwrap();
    let mut ncid = 0;

    let status = unsafe { nc_create(path.as_ptr(), 0, &mut ncid) };
    assert_eq!(status, 0);

    let name = CString::new("num_nodes").unwrap();
    let mut dimid: c_int = 0;

    let status = unsafe { nc_def_dim(ncid, name.as_ptr(), 4_u64, &mut dimid) };
    assert_eq!(status, 0);

    let dimids = [dimid];
    let mut varid: c_int = 0;
    let name = CString::new("coordx").unwrap();

    let status = unsafe {
        nc_def_var(
            ncid,
            name.as_ptr(),
            NC_DOUBLE,
            1,
            dimids.as_ptr(),
            &mut varid,
        )
    };

    let status = unsafe { nc_enddef(ncid) };
    assert_eq!(status, 0, "nc_enddef failed with status={status}");

    let values: [f64; 4] = [1.0, 2.0, 3.0, 4.0];
    let status = unsafe { nc_put_var_double(ncid, varid, values.as_ptr()) };
    assert_eq!(status, 0, "nc_put_var_double failed with status={status}");

    let status = unsafe { nc_close(ncid) };
    assert_eq!(status, 0, "nc_close failed with status={status}");
}

pub fn write<const D: usize, const I: usize, const M: usize, const N: usize, P, T>(
    mesh: &PrimitiveMesh<D, I, M, N, T>,
    path: P,
) -> ResultIO<()>
where
    P: AsRef<Path>,
    T: Copy + Into<usize>,
{
    let path = path.as_ref().to_str().unwrap();
    let path = CString::new(path).unwrap();

    let mut ncid = 0;
    let status = unsafe { nc_create(path.as_ptr(), 0, &mut ncid) };
    assert_eq!(status, 0);

    let api_version: [f32; 1] = [8.25];
    let file_size: [u32; 1] = [1];
    let floating_point_word_size: [u32; 1] = [8];
    let version: [f32; 1] = [8.25];

    let title = CString::new(
        "autotwin.automesh, version 0.3.10, autogenerated on 2026-05-20 16:40:32.893159480 UTC",
    )
    .unwrap();

    let name = CString::new("api_version").unwrap();
    let status = unsafe {
        nc_put_att_float(
            ncid,
            NC_GLOBAL,
            name.as_ptr(),
            NC_FLOAT,
            1,
            api_version.as_ptr(),
        )
    };
    assert_eq!(
        status, 0,
        "nc_put_att_float failed for api_version with status={status}"
    );

    let name = CString::new("file_size").unwrap();
    let status = unsafe {
        nc_put_att_uint(
            ncid,
            NC_GLOBAL,
            name.as_ptr(),
            NC_INT,
            1,
            file_size.as_ptr(),
        )
    };
    assert_eq!(
        status, 0,
        "nc_put_att_uint failed for file_size with status={status}"
    );

    let name = CString::new("floating_point_word_size").unwrap();
    let status = unsafe {
        nc_put_att_uint(
            ncid,
            NC_GLOBAL,
            name.as_ptr(),
            NC_INT,
            1,
            floating_point_word_size.as_ptr(),
        )
    };
    assert_eq!(
        status, 0,
        "nc_put_att_uint failed for floating_point_word_size with status={status}"
    );

    let name = CString::new("title").unwrap();
    let status = unsafe {
        nc_put_att_text(
            ncid,
            NC_GLOBAL,
            name.as_ptr(),
            title.as_bytes().len(),
            title.as_ptr(),
        )
    };
    assert_eq!(
        status, 0,
        "nc_put_att_text failed for title with status={status}"
    );

    let name = CString::new("version").unwrap();
    let status = unsafe {
        nc_put_att_float(
            ncid,
            NC_GLOBAL,
            name.as_ptr(),
            NC_FLOAT,
            1,
            version.as_ptr(),
        )
    };
    assert_eq!(
        status, 0,
        "nc_put_att_float failed for version with status={status}"
    );

    let mut dimid: c_int = 0;
    let name = CString::new("num_dim").unwrap();
    let status = unsafe { nc_def_dim(ncid, name.as_ptr(), D as u64, &mut dimid) };
    assert_eq!(status, 0);

    // Mesh is only built for 1 block, would need to implement Meshes

    let name = CString::new("num_elem").unwrap();
    let status = unsafe {
        nc_def_dim(
            ncid,
            name.as_ptr(),
            mesh.connectivity().len() as u64,
            &mut dimid,
        )
    };
    assert_eq!(status, 0);
    let num_elem_dim_id = dimid;

    let name = CString::new("num_el_blk").unwrap();
    let status = unsafe { nc_def_dim(ncid, name.as_ptr(), 1_u64, &mut dimid) };
    assert_eq!(status, 0);
    let num_el_blk_dim_id = dimid;

    let name = CString::new("num_el_in_blk1").unwrap();
    let status = unsafe {
        nc_def_dim(
            ncid,
            name.as_ptr(),
            mesh.connectivity().len() as u64,
            &mut dimid,
        )
    };
    assert_eq!(status, 0);
    let num_el_in_blk1_dim_id = dimid;

    let name = CString::new("num_nod_per_el1").unwrap();
    let status = unsafe { nc_def_dim(ncid, name.as_ptr(), N as u64, &mut dimid) };
    assert_eq!(status, 0);
    let num_nod_per_el1_dim_id = dimid;

    let name = CString::new("num_nodes").unwrap();
    let status = unsafe {
        nc_def_dim(
            ncid,
            name.as_ptr(),
            mesh.number_of_nodes() as u64,
            &mut dimid,
        )
    };
    assert_eq!(status, 0);
    let num_nodes_dim_id = dimid;

    let name = CString::new("time_step").unwrap();
    let status = unsafe { nc_def_dim(ncid, name.as_ptr(), 0_u64, &mut dimid) };
    assert_eq!(status, 0);

    let mut varid: c_int = 0;

    let cname = CString::new("eb_prop1").unwrap();
    let status = unsafe {
        nc_def_var(
            ncid,
            cname.as_ptr(),
            NC_INT,
            1,
            [num_el_blk_dim_id].as_ptr(),
            &mut varid,
        )
    };
    assert_eq!(status, 0, "nc_def_var failed with status={status}");
    let eb_prop_1_varid = varid;

    let cname = CString::new("connect1").unwrap();
    let status = unsafe {
        nc_def_var(
            ncid,
            cname.as_ptr(),
            NC_INT,
            2,
            [num_el_in_blk1_dim_id, num_nod_per_el1_dim_id].as_ptr(),
            &mut varid,
        )
    };
    assert_eq!(status, 0, "nc_def_var failed with status={status}");
    let connect1_varid = varid;

    let attr_name = CString::new("elem_type").unwrap();
    let attr_value = match [D, M] {
        [3, 2] => CString::new("TRI3").unwrap(),
        _ => panic!(),
    };
    let status = unsafe {
        nc_put_att_text(
            ncid,
            connect1_varid,
            attr_name.as_ptr(),
            4,
            attr_value.as_ptr(),
        )
    };
    assert_eq!(status, 0, "nc_put_att_text failed with status={status}");

    let mut varids = Vec::new();

    match D {
        3 => {
            for name in ["coordx", "coordy", "coordz"] {
                let dimids = [num_nodes_dim_id];
                let cname = CString::new(name).unwrap();

                let status = unsafe {
                    nc_def_var(
                        ncid,
                        cname.as_ptr(),
                        NC_DOUBLE,
                        1,
                        dimids.as_ptr(),
                        &mut varid,
                    )
                };
                assert_eq!(status, 0, "nc_def_var failed with status={status}");
                varids.push(varid);
            }
        }
        _ => unimplemented!(),
    }

    let status = unsafe { nc_enddef(ncid) };
    assert_eq!(status, 0, "nc_enddef failed with status={status}");

    let eb_prop_1 = [1 as c_int];
    let status = unsafe { nc_put_var_int(ncid, eb_prop_1_varid, eb_prop_1.as_ptr()) };
    assert_eq!(
        status, 0,
        "nc_put_var_int failed for eb_prop_1 with status={status}"
    );

    let connect1: Vec<c_int> = mesh
        .connectivity()
        .iter()
        .flat_map(|nodes| nodes.iter().map(|&node| node.into() as c_int + 1))
        .collect();

    let status = unsafe { nc_put_var_int(ncid, connect1_varid, connect1.as_ptr()) };
    assert_eq!(status, 0, "nc_put_var_int failed with status={status}");

    <[Vec<f64>; D]>::from(mesh.coordinates())
        .into_iter()
        .zip(varids)
        .for_each(|(coordinate, varid)| {
            let status = unsafe { nc_put_var_double(ncid, varid, coordinate.as_ptr()) };
            assert_eq!(status, 0, "nc_put_var_double failed with status={status}");
        });

    let status = unsafe { nc_close(ncid) };
    assert_eq!(status, 0, "nc_close failed with status={status}");

    Ok(())
}
