name: Test
on:
  pull_request:
    branches: main
env:
  CARGO_TERM_COLOR: always
jobs:
  Checks:
    strategy:
      fail-fast: false
      matrix:
        features: [math, mechanics, constitutive, fem]
        os: [macos-latest, windows-latest, ubuntu-latest]
        toolchain:
          - beta
          - nightly
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          default: true
          toolchain: ${{ matrix.toolchain }}
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --release --features ${{ matrix.features }} -- -D warnings
      - name: Lint tests
        run: cargo clippy --release --features ${{ matrix.features }} --tests -- -D warnings
      - name: Test
        run: cargo test --release --features ${{ matrix.features }}
  Coverage:
    strategy:
      fail-fast: false
      matrix:
        features: [math, mechanics, constitutive, fem]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: LLVM-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Coverage
        run: rustup run nightly cargo llvm-cov --profile release --features ${{ matrix.features }} --fail-under-functions 70 --fail-under-lines 75 --fail-under-regions 70
      - name: Tree
        run: $([[ $(cargo tree --color always --edges normal --features ${{ matrix.features }} | wc -l) -eq 1 ]])
  Mutants:
    strategy:
      fail-fast: false
      matrix:
        features: [math]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: taiki-e/install-action@cargo-mutants
      - name: Mutants
        run: cargo mutants --features ${{ matrix.features }} --profile release --minimum-test-timeout 0.9
